/* Generated By:JavaCC: Do not edit this line. BasicLTreeConstants.java Version 5.0 */
public interface BasicLTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTFUNCTION_DECL = 5;
  public int JJTPARAMS = 6;
  public int JJTTYPE = 7;
  public int JJTMAIN = 8;
  public int JJTASSIGN = 9;
  public int JJTADD = 10;
  public int JJTMULT = 11;
  public int JJTBOOLOPP = 12;
  public int JJTCONDITION = 13;
  public int JJTID = 14;
  public int JJTNUM = 15;
  public int JJTBOOL = 16;
  public int JJTFUNCTIONCALL = 17;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Decl",
    "ConstDecl",
    "Function",
    "Function_Decl",
    "Params",
    "Type",
    "Main",
    "Assign",
    "Add",
    "Mult",
    "BoolOpp",
    "Condition",
    "Id",
    "Num",
    "Bool",
    "FunctionCall",
  };
}
/* JavaCC - OriginalChecksum=38d46098b8e7fca800557e212fe55238 (do not edit this line) */
