/* Generated By:JavaCC: Do not edit this line. BasicLVisitor.java Version 5.0 */
public interface BasicLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTId node, Object data);
  public Object visit(ASTNum node, Object data);
  public Object visit(ASTBool node, Object data);
}
/* JavaCC - OriginalChecksum=2701804836c9df701e89264a4112b43e (do not edit this line) */
